Add `overline` style, remove `keyword`, `hsl`, `hsv`, `hwb` and `ansi` style and stop backporting `ansi256` to `ansi` on older terminals
chalk/chalk pull request #433
Opened 2021-04-17 14:31 UTC by Richienb

2021-04-18 09:52 UTC, Richienb commented
Because desampling to `ansi` is no longer active, level 1 is now effectively the same in function as level 2.

2021-04-18 23:52 UTC, Qix- commented
Just curious, why aren't we downsampling anymore? That seems like a functional regression, given that there are still _loads_ of terminals that only support the older 16 color palette.

2021-04-18 23:53 UTC, Richienb commented
Because you said so

2021-04-19 00:01 UTC, Qix- commented
I don't see in there why we need to remove this functionality. I would say we should inline that from `color-convert` (you're free to copy over the `ansi256.ansi16` function from `conversions.js` directly - not that the license would have prevented you anyway). Just mention it came from `color-convert` in a comment.

The concern about upscaling (#370) was valid, but downscaling is absolutely necessary to keep compatibility with people who do not have 256 support.

2021-04-19 00:49 UTC, Richienb commented
> you're free to copy over the `ansi256.ansi16` function from `conversions.js` directly - not that the license would have prevented you anyway

That function doesn't exist

2021-04-19 04:58 UTC, Qix- commented
Right, you have to merge them - this is untested but should be close enough. Just needs a bit of polish for the Chalk conventions.

```javascript
function ansi256To16(args) {
	let r, g, b;

	// Handle greyscale
	if (args >= 232) {
		const c = (args - 232) * 10 + 8;
		r = g = b = c / 255;
	} else {
		args -= 16;

		let rem;
		r = Math.floor(args / 36) / 5;
		g = Math.floor((rem = args % 36) / 6) / 5;
		b = (rem % 6) / 5;
	}

        const value = Math.max(r, g, b) * 2;

	if (value === 0) {
		return 30;
	}

	let ansi = 30
		+ ((Math.round(b) << 2)
		| (Math.round(g) << 1)
		| Math.round(r));

	if (value === 2) {
		ansi += 60;
	}

	return ansi;
}
```

2021-04-21 11:17 UTC, Richienb commented
Support for `ansi` has been added back in.

2021-04-21 13:26 UTC, Qix- approved these changes
I don't see anything glaringly wrong with the code; I'll let Sindre have the final look.

2021-04-21 13:36 UTC, sindresorhus commented
I'm confused. I understand preserving the downsampling, but shouldn't we still remove the explicit `.ansi()` method?

2021-04-21 13:39 UTC, Richienb commented
IMO, there is no impact of leaving the function there so we might as well leave it for people wanting to use the `ansi` color space.

2021-04-21 13:46 UTC, Qix- commented
People wanting to use the `ansi` color space should just use `.red()`, `.blueBright()`, etc as it's a 1:1 mapping. People doing programmatic generation of colors for whatever reason are going to be using 256 or truecolor - not 16 - as there is no logical rhyme or reason to the code (I always remember them as "traffic light, dark blue, pink, light blue, white" - completely arbitrary).

I agree with sindre here - no need for `.ansi()`. Chalk is a utility library, after all - you're always able to write escapes yourself with trivial syntax.

2021-04-21 13:52 UTC, Richienb commented
Removed

2021-04-21 15:38 UTC, sindresorhus approved these changes

2021-04-22 03:50 UTC, Qix- requested changes

2021-04-22 03:50 UTC, Qix- commented on index.d.ts
> +	Use a [8-bit unsigned number](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) to set text color.
```suggestion
	Use an [8-bit unsigned number](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) to set text color.
```

2021-04-22 03:50 UTC, Qix- approved these changes
LGTM

2021-04-22 03:54 UTC, merged

2021-04-22 03:55 UTC, sindresorhus commented
Nice work, @Richienb 👍

2021-04-22 07:33 UTC, Qix- commented
Yes indeed :) Thanks @Richienb, super appreciated.